### ISSUE TITLE
Error when compiling gscript

### ISSUE THREAD

**Issue by jayhill365** [ahhh/gscripts#3]
Getting this error message when trying to compile a binary using gscipt 

main.go:10:2: cannot find package "github.com/gen0cide/gscript/engine" in any of:
	/usr/local/go/src/github.com/gen0cide/gscript/engine (from $GOROOT)
	/Users/pwngrillz/go/src/github.com/gen0cide/gscript/engine (from $GOPATH)
[GSCRIPT:compiler] 2018-20-24 10:20:16 PM (PDT) FATAL Compilation error for /var/folders/p9/hcl_yxtx1q5_4lgtrflygfnh0000gn/T/gPRhCKImrkqhkTjh/main.go

**Comment by nullmonk** [comment]
I believe that is what happens when you try to compile without passing in any scripts. May we see the command you are calling?

**Comment by jayhill365** [comment]
@micahjmartin yea sure! 

This is the command i'm calling;

pwngrillzs-MBP:gscript_0.0.19_darwin_amd64 pwngrillz$ ./gscript c test.gs 

test.gs is really just the grab_clipboard.gs script which I found in the attacks/osx folder I just renamed it test.gs

**Comment by jayhill365** [comment]
@micahjmartin found out what was wrong. Fixed the issue by making sure go get was working first then I grabbed go-bindata and grabbed gscript again:
 
go get -u github.com/jteeuwen/go-bindata/...
go get github.com/gen0cide/gscript/cmd/gscript

Now everything works just pushed a new commit check it out !

**Comment by nullmonk** [comment]
@jayhill365 Awesome good to hear
